# Copyright (c) 2016, Tom Honermann
#
# This file is distributed under the MIT License. See the accompanying file
# LICENSE.txt or http://www.opensource.org/licenses/mit-license.php for terms
# and conditions.

sudo: false
language: cpp

env:
  global:
   # encrypted COVERITY_SCAN_TOKEN:
   - secure: "D9N0aj5XBLXVRru7yF1/TXvEuejKwe0XPyY/S756p3l5hM+bQPeAqDfD3f1vvjx3HA9sTrxFHRnj1MNK81Eeed/w6zzrdl09ufVf/AxxzpHQWlCdNK+5p3PKrOOfOW1IugjzVq/ScV2KlW+teZ3vKr5Csfbqk4fi9ER3JYGJ8DZaShvKsYrXYhPOlSOgNYYIoorhtB3sNHHYUwC83tJ97kHSSOSrWc5xDXGiEJVwgKd1AbOJwuTVIp9bIzLWJmmJBR4k3WsrSlrYvchAZF9mvk3qmk11FuW1pfTmtOS1CAklkTLRjfAM83b5wgUBiwEXFESn+Nwx3rWvAsdoHCUOsDJyS3oX6UR0T0r087GCOh4dOo+Yv6HMU/oM/7pxIs28q1eoi3Sh0XCKbA8JlSraL65RM7puD1OOR8sXyJCj4p3xkKsd/IkbYCdkrlkGtv3mztLWzDLQRVTBpz5VpSloC0p0GX3ISUzL3YlJbjPAfPYF2qsMOOI4GWnmp0QnicS/hHaePmjYAQ2LdYw4R3mEaRCnjeZ4+zvWE0c/ku4QebXoSuHWFP4wIXArvCyIticBXxmn1GI3bjK4d3V09j+i6OpQJi/a6UpEeSW1jyrikIK2vnhjmFSiv0mvwF7xNb9drvwVuZU659pEl/rD5ZMYWy+q4wzK49fw2AMCrSRjoZE="

matrix:
  include:
    - os: linux
      addons:
        apt:
          packages:
            - g++-6
          sources:
            - ubuntu-toolchain-r-test
        coverity_scan:
          project:
            name: "tahonermann/text_view-range-v3"
            description: "A range-v3 based character encoding and code point enumeration library"
          notification_email: tom@honermann.net
          build_command_prepend: "sh -c 'mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=RELEASE ..'"
          build_command: "sh -c 'cd build && cmake --build . --config RELEASE'"
          branch_pattern: coverity_scan
      compiler: gcc
      env: COMPILER=g++-6 BUILD_TYPE=RELEASE

cache:
  directories:
    - cache

install:
  - |
    if [ "${TRAVIS_OS_NAME}" == "linux" ]; then
      if [ "!" -x cache/cmake/bin/cmake ]; then
        CMAKE_URL="http://www.cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz"
        mkdir -p cache/cmake
        travis_retry wget --no-check-certificate --quiet -O - "${CMAKE_URL}" | tar --strip-components=1 -xz -C cache/cmake
      fi
      export PATH="$TRAVIS_BUILD_DIR/cache/cmake/bin:$PATH"
    elif [ "${TRAVIS_OS_NAME}" == "osx" ]; then
      if "!" brew ls --version cmake; then
        brew install cmake
      fi
    fi
  - travis_retry git clone https://github.com/ericniebler/range-v3.git range-v3
  - export RANGE_V3_INSTALL_PATH="$TRAVIS_BUILD_DIR/range-v3"

before_script:
  - uname -a
  - which cmake
  - cmake --version
  - export CXX="$COMPILER"
  - echo "CXX=$CXX"
  - which $CXX
  - $CXX --version
  - "echo \"range-v3 commit: $(git -C range-v3 rev-parse HEAD)\""

script:
  - echo "Skipping regular build since Coverity Scan is active"
